"""
Django settings for engineai project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-94f6_#wds%jlajz)e+u^7+^px9*1i9aex&sf)atmovbs6n(tj0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'engineai',
    'aichat',
    'channels',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'engineai.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'engineai.wsgi.application'
ASGI_APPLICATION = 'engineai.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Channels
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}


# mysite/settings.py
UNFOLD = {
    # 基础（你已有）
    "SITE_TITLE": "EngineAI",
    "SITE_HEADER": "管理后台",
    
    # 新增：启用命令面板（Ctrl+K 快速搜索模型，像 VS Code）
    "COMMANDS_ENABLED": True,  # 2025 新特性：Web 版命令行
    
    # 新增：自定义仪表盘（首页变统计页）
    "DASHBOARD_ENABLED": True,
    "DASHBOARD_STATS": [  # 简单配置：添加卡片/图表
        {
            "title": "总文章数",
            "value": lambda: Article.objects.count(),  # 动态查询
            "icon": "pen-tool",  # Unfold 图标
            "color": "blue",
        },
        {
            "title": "最近用户",
            "type": "list",  # 列表组件
            "model": "auth.User",
            "limit": 5,
        },
    ],
    
    # 新增：高级过滤全局开启
    "ADVANCED_FILTERS": True,  # 所有 list_filter 变高级版
    
    # 新增：集成 Crispy Forms（更美表单）
    "CRISPY_TEMPLATE_PACK": "unfold",  # 如果你用 django-crispy-forms
    
    # 新增：UI 组件（卡片、按钮重用）
    "COMPONENTS": {
        "cards": True,  # 仪表盘卡片
        "charts": True,  # 需额外 JS，如 Chart.js
    },
    
    # 2025 新：Studio 插件（可视化自定义，无代码改颜色/布局）
    "STUDIO_ENABLED": True,  # pip install django-unfold-studio（可选付费）
}

# settings.py 最后加上（可选）
import os
os.environ.setdefault("OPENROUTER_API_KEY", "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")